version: '3.4'

services:
  wk.catalog.db:
    hostname: catalogdb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: C@talog
    volumes: 
      - /c/temp/datadb:/var/lib/mysql

networks:
  default:
    name: service_catalog